# Generated by Django 5.1.1 on 2024-09-26 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_categoria', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('nombre_categoria', models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categoría',
                'db_table': 'categoria',
                'ordering': ['nombre_categoria'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_pais', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('nombre_pais', models.CharField(blank=True, max_length=100, null=True, verbose_name='País')),
                ('nombre_pais_ingles', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('nombre_pais_frances', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays')),
                ('continente', models.CharField(choices=[('América', 'América'), ('Europa', 'Europa'), ('Asia', 'Asia'), ('África', 'África'), ('Oceanía', 'Oceanía'), ('Antártida', 'Antártida'), ('', 'Seleccione una opción')], default='América', max_length=15, verbose_name='Continente')),
                ('codigo_telefonico', models.CharField(blank=True, max_length=5, null=True, verbose_name='Código Telefónico')),
                ('codigo_iso2', models.CharField(blank=True, max_length=2, null=True, verbose_name='Código ISO2')),
                ('codigo_iso3', models.CharField(blank=True, max_length=3, null=True, verbose_name='Código ISO3')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Paises',
                'db_table': 'pais',
                'ordering': ['nombre_pais'],
            },
        ),
        migrations.CreateModel(
            name='TipoBiblioteca',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_tipo_biblioteca', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_tipo_biblioteca', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('nombre_tipo_biblioteca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Biblioteca')),
            ],
            options={
                'verbose_name': 'Tipo de Biblioteca',
                'verbose_name_plural': 'Tipos de Biblioteca',
                'db_table': 'tipo_biblioteca',
                'ordering': ['nombre_tipo_biblioteca'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_tipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_tipo_documento', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('nombre_tipo_documento', models.CharField(blank=True, max_length=40, null=True, verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'db_table': 'tipo_documento',
                'ordering': ['nombre_tipo_documento'],
            },
        ),
        migrations.CreateModel(
            name='TipoEditor',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_tipo_editor', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_tipo_editor', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('nombre_tipo_editor', models.CharField(blank=True, max_length=40, null=True, verbose_name='Tipo de Editor')),
                ('observacion_tipo_editor', models.CharField(blank=True, max_length=80, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Tipo de Editor',
                'verbose_name_plural': 'Tipos de Editor',
                'db_table': 'editor',
                'ordering': ['nombre_tipo_editor'],
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_subcategoria_producto', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_subcategoria', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('nombre_subcategoria', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sub Categoría')),
                ('id_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.categoria')),
                ('id_tipo_biblioteca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.tipobiblioteca')),
            ],
            options={
                'verbose_name': 'Sub Categoría',
                'verbose_name_plural': 'Sub Categorías',
                'db_table': 'sub_categoria',
                'ordering': ['nombre_subcategoria'],
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='id_tipo_biblioteca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.tipobiblioteca'),
        ),
    ]
